name: Dependabot Lockfile Update

on:
  pull_request:
    paths:
      - 'package.json'
      - 'apps/**/package.json'
      - 'packages/**/package.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lockfile:
    name: Update lockfile
    runs-on: ubuntu-latest
    # Only run on Dependabot PRs
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update lockfile
        run: bun install --no-save

      - name: Check for lockfile changes
        id: check-changes
        run: |
          if git diff --quiet bun.lock; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No lockfile changes needed"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Lockfile has changes"
          fi

      - name: Commit lockfile
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config user.name "dependabot[bot]"
          git config user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git add bun.lock
          git commit -m "chore: update bun.lock"
          git push
