name: 🚀 Release Web

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "packages/ui/**"
      - ".github/workflows/release-web.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        type: choice
        required: true
        default: "staging"
        options:
          - staging
          - production

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  # ==============================================
  # Deploy to Vercel
  # ==============================================
  deploy:
    name: 🚀 Deploy to Vercel
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🧰 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Install Dependencies
        run: bun install --frozen-lockfile

      - name: 🏗️ Build Web App
        run: bun run build:web
        env:
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}

      - name: 🚀 Deploy to Vercel (Staging)
        if: github.event.inputs.environment != 'production'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
          alias-domains: staging-{{BRANCH}}.vercel.app

      - name: 🚀 Deploy to Vercel (Production)
        if: github.event.inputs.environment == 'production'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
          vercel-args: "--prod"

      - name: 📊 Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ secrets.NEXT_PUBLIC_APP_URL }}
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: 💬 Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              ### 🚀 Web App Deployed!

              **Environment:** ${{ github.event.inputs.environment || 'staging' }}
              **URL:** ${{ secrets.NEXT_PUBLIC_APP_URL }}
              **Commit:** \`${context.sha.substring(0, 7)}\`

              View deployment logs in the [Actions tab](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
              `
            })